name: CI
on: [push, pull_request]

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-gnu"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo build --locked --release --target ${{ matrix.target }}
      - run: cargo fmt --check
      - run: cargo clippy --no-deps
